spring:
  application:
    name: qwikpay

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:qwikpaydb;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
   # platform: h2

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Config Server - Disable if not used
  cloud:
    config:
      enabled: false

# JWT Configuration
jwtSecret: BLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURU
jwtExpirationMs: 86400000

# Logging Configuration
logging:
  # File logging configuration
  file:
    name: logs/app.log  # Log file location and name
  
  # Logback rolling policy configuration
  logback:
    rollingpolicy:
      # Define the pattern for rolling log file names (logs will be based on date and index)
      file-name-pattern: logs/%d{yyyy-MM-dd}.%i.log
      # Maximum size of each log file before it rolls over
      max-file-size: 10MB
      # Maximum total size of all log files before older ones are deleted
      total-size-cap: 1GB
      # Maximum number of log file history (older files are deleted after this limit)
      max-history: 10

# MySQL Configuration (Commented out for now)
# datasource:
#   url: jdbc:mysql://localhost:3306/qwikpaydb15?createDatabaseIfNotExist=true
#   username: root
#   password: root

# jpa:
#   properties:
#     hibernate:
#       dialect: org.hibernate.dialect.MySQLDialect
#   hibernate:
#     ddl-auto: update
#   show-sql: true
